Scifabric/pybossa

.travis.yml

install coveralls after success

---

pybossa/view/flickr.py

Use read permision in Flickr Oauth.

---

cli.py

This is a cli method to delete old accounts that were registered in the system without the email account validation.

Delete hard-bounces from server.

---

pybossa/core.py
test/test_i18n.py

Read the language from a cookie created by the web server (Apache or Nginx).

Issue language cookie

---

pybossa/api/__init__.py
pybossa/view/applications.py
setup.py
test/test_request_task_to_contribute.py
test/test_web.py

Issue 1023 task links

---

pybossa/jobs.py
test/test_jobs/__init__.py
test/test_jobs/test_app_stats.py
test/test_jobs/test_engage_old_users.py
test/test_jobs/test_export.py
test/test_jobs/test_import_tasks.py

This is a major improvement to reduce the impact on memory.

Refactor to use yield instead of lists.

---

.travis.yml
doc/install.rst
provisioning/playbook.yml

rq-scheduler 0.5.1 uses some "wheel" package which is not compatible to older pip

upgrade pip itself for rq-scheduler

---

pybossa/core.py
pybossa/jobs.py
test/test_jobs/__init__.py
test/test_jobs/test_export.py

Review also submodules: PyBossa/pybossa-default-theme#67 and PyBossa/crowdcrafting-theme#96

Jobs refactor

---

pybossa/view/admin.py
test/test_admin.py

issue 1042 category creation failing

---

pybossa/jobs.py
pybossa/newsletter/__init__.py
pybossa/uploader/rackspace.py
pybossa/view/account.py
pybossa/view/applications.py
pybossa/view/facebook.py
pybossa/view/google.py
pybossa/view/twitter.py
test/test_newsletter.py
test/test_web.py

As usual, review and merge too submodule PRs: PyBossa/pybossa-default-theme#70 and PyBossa/crowdcrafting-theme#104

Account Refactor

---

pybossa/importers.py
test/default.py
test/test_importers.py
test/test_web.py

Issue 1050 encoding errors

---

pybossa/util.py
pybossa/view/facebook.py
pybossa/view/google.py
pybossa/view/twitter.py
test/test_facebook.py
test/test_google.py
test/test_twitter.py
test/test_util.py
test/test_web.py

Fixes #1049.
Review and merge submodules too: PyBossa/crowdcrafting-theme#105 and PyBossa/pybossa-default-theme#71

Issue 1049 fb signup

---

pybossa/api/task.py
pybossa/cache/apps.py
pybossa/exporter/__init__.py
pybossa/importers.py
pybossa/uploader/__init__.py
pybossa/uploader/local.py
pybossa/uploader/rackspace.py
pybossa/view/applications.py
test/test_uploader/test_local_uploader.py
test/test_uploader/test_rackspace_uploader.py
test/test_web.py

Fixes #1055
Fixes #1057 
Fixes #983

Issue 1057 refresh cache

---

pybossa/core.py

Use gettext instead of lazy_gettext for flash message

---

pybossa/forms/forms.py
pybossa/view/projects.py

Issue 1072 empty description

---

pybossa/forms/forms.py
test/test_forms.py

Issue 1064 email length

---

cli.py

Fixed indent error crashing vagrant up

Fixed indent error

---

.gitignore
doc/installing_pybossa.rst
doc/plugins.rst
pybossa/core.py
pybossa/extensions.py
pybossa/forms/forms.py
pybossa/sched.py
setup.py
test/test_auditlog.py
test/test_sched.py
test/test_web.py

Please, check also https://github.com/PyBossa/random-scheduler as an example of a scheduler for PyBossa as a plugin.

Issue plugins

---

README.md

This will allow scientists and researchers to cite our software using DOIs.

Add DOI from Zenodo

---

.landscape.yaml
.prospector.yaml
cli.py
pybossa/dashboard.py
pybossa/jobs.py
pybossa/view/admin.py
test/default.py
test/test_admin.py
test/test_jobs/test_dashboard_active_anon_week.py
test/test_jobs/test_dashboard_active_users_week.py
test/test_jobs/test_dashboard_projects_week.py
test/test_jobs/test_dashboard_task_task_run.py
test/test_jobs/test_dashboard_users.py

This pull request adds a dashboard to the Admin view, so admins can have in one place an idea about what's going on in PyBossa.

Issue dashboard

---

pybossa/cache/projects.py
pybossa/jobs.py
pybossa/util.py
pybossa/view/help.py
pybossa/view/projects.py
test/test_cache/test_cache_projects.py
test/test_util.py

Simple system to rank projects based on their activity and appeal (due to number of volunteers, tasks, if it's a test or not, if has an avatar, or if it's completed).
Review and merge this too: PyBossa/crowdcrafting-theme#145

Issue rank projects

---

pybossa/importers.py
test/test_importers.py

Issue 1106 malformed csvs

---

pybossa/sentinel/__init__.py
setup.py

Revert "Issue 1029 redis py update"

---

README.md
doc/api.rst
doc/changelog/v0.2.3.rst
pybossa/api/api_base.py
pybossa/repositories/blog_repository.py
pybossa/repositories/project_repository.py
pybossa/repositories/task_repository.py
pybossa/repositories/user_repository.py
test/test_api/test_api_common.py
test/test_api/test_category_api.py
test/test_api/test_task_api.py
test/test_api/test_taskrun_api.py

See this for more info: http://use-the-index-luke.com/no-offset

Use keyset pagination instead of offset.

---

pybossa/cache/helpers.py
pybossa/view/projects.py
test/test_cache/test_cache_helpers.py
test/test_web.py

Closes #1134 
Review and merge also PyBossa/pybossa-default-theme#85

Issue 1134 empty presenter

---

pybossa/cache/projects.py

This new query improves the speed by more than 50% (in the biggest project around 53%) just using subqueries.

Use new SQL to speed up task browse pages.

---

pybossa/model/project.py

Add for default an empty dict.

---

pybossa/cache/helpers.py

This PR pass the number of blog posts of a project to the object (using the same method that for knowing which contrib button to show).

Add number of blogposts.

---

pybossa/jobs.py
pybossa/model/event_listeners.py
test/test_jobs/test_notify_blog_users.py
test/test_model/test_event_listeners.py

This PR will send an email to users who want to receive notifications from PyBossa when a project posts a new blog. 
The email will look like this on Crowdcrafting:

Issue 1152 send updates to users

---

doc/customizing.rst
pybossa/cache/project_stats.py
pybossa/core.py
pybossa/default_settings.py
pybossa/jobs.py
settings_local.py.tmpl
setup.py
test/test_jobs/__init__.py
test/test_jobs/test_weekly_update.py

Issue weekly stats

---

pybossa/core.py

This commit checks first the user preferred language from the browser. Then
it checks for the language Cookie. If the cookie is empty, the user language is
used, otherwise the cookie one.

Add user locales.

---

pybossa/view/facebook.py
pybossa/view/google.py
pybossa/view/twitter.py
test/test_facebook.py
test/test_google.py
test/test_twitter.py

Issue 1167 oauth tokens

---

doc/customizing.rst
doc/translating.rst
pybossa/core.py
pybossa/default_settings.py
pybossa/forms/forms.py
settings_local.py.tmpl
settings_test.py

Refactor how locales are assigned for PyBossa.

Issue locales

---

pybossa/core.py

Avoid using a variable that may have not been initialized

---

settings_local.py.tmpl

Add Brazilian Portuguese to locale settings

Add new locales settings.

---

doc/user/pbs.rst
doc/user/tutorial.rst

Merge also theme submodules PRs: PyBossa/crowdcrafting-theme#233 and PyBossa/pybossa-default-theme#100

Fixes in docs and in theme templates

---

setup.py

see https://github.com/rackspace/pyrax/issues/575

fix error with pyrax underlying libraries

---

setup.py

see https://github.com/rackspace/pyrax/issues/575

upgrade pyrax for unpinning python-novaclient

---

cli.py
pybossa/forms/forms.py
pybossa/view/projects.py
test/helper/web.py
test/test_auditlog.py
test/test_web.py

Please, review submodule PRs too: PyBossa/pybossa-default-theme#103 and PyBossa/crowdcrafting-theme#244

Script for hidden projects

---

pybossa/jobs.py
test/test_jobs/test_engage_old_users.py

This PR fixes the emails contacting inactive users.

Issue 1206 quaterly emails

---

pybossa/jobs.py
test/test_jobs/test_old_projects.py

Exclude completed projects from inactive jobs.

Issue 1214 inactive jobs

---

pybossa/view/twitter.py
test/test_twitter.py

Issue 1240 fix twitter login callback

---

doc/user/overview.rst
pybossa/api/task_run.py
pybossa/auth/taskrun.py
pybossa/model/event_listeners.py
pybossa/repositories/task_repository.py
pybossa/view/projects.py
test/test_api/test_taskrun_api.py
test/test_authorization/test_taskrun_auth.py
test/test_repository/test_task_repository.py
test/test_view/test_project_publish.py

Also review theme PR: https://github.com/PyBossa/crowdcrafting-theme/pull/301 and https://github.com/PyBossa/pybossa-default-theme/pull/116.

Allow to store answers for draft projects and flush them before publishing

---

test/test_jobs/test_engage_old_users.py

Add the new logos to the docs theme.

New theme.

---

pybossa/view/projects.py
setup.py

Check that users have read rights to access the export CSV, JSON formats for tasks and task_runs.

Issue security

---

.travis.yml

travis git submodule workaround

---

doc/api.rst

see
http://docs.pybossa.com/en/latest/api.html#example-usage

fix docs on API.

---

pybossa/model/event_listeners.py
test/test_model/test_event_listeners.py

Ensure that when a result is created, the webhook notifies the latest Result ID.

Fixes webhooks

---

doc/api.rst
pybossa/core.py
pybossa/messages.py
pybossa/util.py
pybossa/view/account.py
test/helper/web.py
test/test_util.py
test/test_web.py

This is the work for solving issue #1344

Issue 1344 account update

---

.travis.yml
doc/api.rst
pybossa/messages.py
pybossa/view/account.py
test/helper/web.py
test/test_admin.py
test/test_web.py

Issue 1335 account signin

---

requirements.txt
setup.py

Upgrade webassets to newest version for Jinja 2.9
See https://github.com/miracle2k/webassets/issues/477

fix for webassets with Jinja 2.9

---

doc/api.rst
pybossa/util.py
pybossa/view/admin.py
test/test_admin.py

Issue 1350 admin users

---

doc/api.rst
pybossa/view/help.py
test/test_web.py

Note:
no readability version for license text. It produces wrong selected html content :(

Issue 1393 help license

---

doc/api.rst
pybossa/view/help.py
test/test_web.py

Issue 1395 cookies policy

---

contrib/supervisor/rq-worker.conf.template
doc/customizing.rst
doc/install.rst
provisioning/templates/rq-worker.conf.j2
pybossa/core.py
pybossa/default_settings.py
pybossa/jobs.py
settings_local.py.tmpl
test/test_jobs/test_maintenance.py

Issue 1442 mail admins background jobs fails

---

doc/api.rst
pybossa/view/account.py
test/test_web.py

Fix register json

---

pybossa/vmcp.py
setup.py
test/test_api/test_vmcp_api.py
test/test_vmcp.py

This pull request replaces the m2crypto package with the rsa package (ref #1466). All tests should be passing.

replace m2crypto with rsa (fixes #1466)

---

doc/api.rst
doc/user/project_settings.rst
pybossa/api/__init__.py
pybossa/api/task_run.py
pybossa/sched.py
test/test_sched.py
test/test_sched_2.py

Incremental scheduler should be removed. It's not maintained at all.

Newtask desc orderby

---

pybossa/core.py
pybossa/util.py
pybossa/view/account.py
pybossa/view/projects.py
test/test_util.py

Issue 1480 fix missing content type

---

doc/user/project_settings.rst
pybossa/sched.py
test/test_sched.py

Create a test for checking that state='completed' is respected.

Issue sched depth

---

pybossa/exporter/json_export.py

This avoids using Yield and uses directly the SQAlchemy all() method. It has proven to be much faster.

Improve performance.

---

doc/customizing.rst
pybossa/api/api_base.py
pybossa/api/project.py
pybossa/default_settings.py
pybossa/jobs.py
pybossa/model/__init__.py
pybossa/model/event_listeners.py
pybossa/model/project.py
pybossa/view/projects.py
setup.py
test/factories/project_factory.py
test/test_activity_update.py
test/test_api/test_api_common.py
test/test_api/test_project_api.py
test/test_authorization/test_blogpost_auth.py
test/test_cache/test_cache_users.py
test/test_hateoas.py
test/test_jobs/test_onesignal.py
test/test_model/test_event_listeners.py
test/test_privacy.py
test/test_repository/test_blog_repository.py
test/test_repository/test_project_repository.py
test/test_view/test_blog.py
test/test_view/test_project_passwords.py
test/test_web.py

This PR will create OneSignal apps for every new project created.

Add webpush notifications

---

.travis.yml
pybossa/cache/users.py

It tries to read first, if it fails, then it creates the
materialized view.

Fix issue #1555

---

pybossa/model/event_listeners.py

This makes the query from 120ms to 0.03ms.

Improve the query.

---

pybossa/view/projects.py

Be sure that we clean the cache after publishing the project.

Fix #1582.

---

pybossa/view/admin.py

Just realized I left out two `Markup`s

addtl markup

---

pybossa/view/account.py
settings_local.py.tmpl
test/test_web.py

Ensure that we can generate different safe links to recover a password.

Fix issue #1646.

---

pybossa/forms/forms.py

Add media_url and published to AnnouncementForm

---

pybossa/view/admin.py

I rushed the previous update of the Announcement form, this should fix it!

Fix create/update Announcement via form

---

alembic/versions/acea90f77ba3_added_owners_list_to_project_table.py
pybossa/api/project.py
pybossa/auth/auditlog.py
pybossa/auth/blogpost.py
pybossa/auth/project.py
pybossa/auth/result.py
pybossa/auth/task.py
pybossa/auth/webhook.py
pybossa/cache/users.py
pybossa/model/project.py
pybossa/password_manager.py
pybossa/repositories/project_repository.py
pybossa/repositories/user_repository.py
pybossa/view/projects.py
test/default.py
test/factories/project_factory.py
test/test_api/test_project_api.py
test/test_coowners.py
test/test_password_manager.py
test/test_repository/test_user_repository.py

Hello,
We developed this feature to give project owners the ability to add 'co-owners' to their project; a co-owner is a user that has the same access level to the project as the owner.
Please let me know what you think about it.

Project owner can create co-owners

---

pybossa/repositories/__init__.py
test/test_api/test_api_announcement.py

When a logged in user tries to access the announcements API it fails. This solves it.

Issue 1701

---

pybossa/api/__init__.py
pybossa/api/api_base.py
pybossa/api/project_stats.py
pybossa/auth/__init__.py
pybossa/auth/projectstats.py
pybossa/core.py
pybossa/hateoas.py
pybossa/repositories/__init__.py
pybossa/repositories/project_stats_repository.py
test/test_api/test_api_project_stats.py
test/test_authorization/test_projectstats_auth.py
test/test_repository/test_projectstats_repository.py

Issue 1712

---

pybossa/sched.py
test/test_sched_depth_first_all.py

This adds a new scheduler that will allow users to contribute to completed tasks. It's the same as the default one but without taking into account if the task.state is completed. This scheduler could be useful for completed projects that want to show how it worked afterward.

Issue 1713

---

pybossa/model/event_listeners.py
test/test_model/test_event_listeners.py

[Docs](https://github.com/Scifabric/docs.pybossa.com/pull/15)

Issue 1734

---

pybossa/api/user.py
test/test_api/test_user_api.py

Issue 1739

---

pybossa/forms/forms.py

It ensures that strong password is used at every single place.

Fixes #1743.

---

pybossa/util.py
pybossa/view/facebook.py
pybossa/view/google.py
pybossa/view/twitter.py
test/test_util.py
test/test_view/test_facebook.py
test/test_view/test_google.py
test/test_view/test_twitter.py

Issue 1676

---

pybossa/cache/projects.py
pybossa/cache/users.py
pybossa/exporter/csv_reports_export.py
pybossa/view/projects.py
test/test_project_report.py

Hello,
We've developed a feature that can generate project report in csv form. This report has two parts containing information on project and users contributed to that project. Hope you find it useful.
The sample report would look like,
Project Statistics |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Id | Name | Short Name | Total Tasks | First Task Submission | Last Task Submission | Average Time Spend Per Task | Task Redundancy
2 | Company Description | companydescription | 150 | 2017-11-11T11:50:28.479330 | 2017-11-13T19:39:21.365752 | 0.11 | 1
  |   |   |   |   |   |   |  
User   Statistics |   |   |   |   |   |  
Id | Name | Fullname | Total Tasks Completed | Percent Tasks Completed | First Task Submission | Last Task Submission | Average Time Per Task
1 | user_3 | user_3 …

Generate on demand project report

---

pybossa/uploader/__init__.py
pybossa/util.py
test/test_util.py
test/test_web.py

Allow to do the cropping on the front end. Also include the full
external URL for user avatars.

Fix issue #1524.

---

pybossa/view/projects.py
test/test_view/test_project_publish.py

Use handle_content_type for publishing projects

---

pybossa/cache/users.py
pybossa/view/home.py
pybossa/view/projects.py
test/test_web.py

Add the ability to view historical contributions from the home page.

Add historical contributions category and to home page

---

pybossa/jobs.py

Add check for no entries in news job

---

.gitmodules
alembic/versions/d317dc38cf39_add_user_pref_to_user.py
pybossa/cache/users.py
pybossa/core.py
pybossa/forms/fields/__init__.py
pybossa/forms/fields/time_field.py
pybossa/forms/forms.py
pybossa/forms/validator.py
pybossa/jobs.py
pybossa/model/user.py
pybossa/util.py
pybossa/view/account.py
requirements.txt
requirementsdocs.txt
settings_local.py.tmpl
settings_upref_mdata.py.tmpl
setup.py
test/test_forms.py
test/test_jobs/test_news.py
test/test_web.py

increase version number and minor fixes. Merges https://github.com/Scifabric/pybossa/pull/1789 and https://github.com/Scifabric/pybossa/pull/1784

Bloomberg feature upref mdata

---

pybossa/cache/users.py

Delete sneaky commas

---

pybossa/view/account.py

Add missing metadata form

---

contrib/supervisor/rq-scheduler.conf.template

It should be --db 0 so if people copy and paste this file, the config will work.

Fix --db flag

---

pybossa/forms/forms.py
pybossa/importers/iiif.py
pybossa/importers/importer.py
test/test_importers/__init__.py
test/test_importers/test_iiif_importer.py
test/test_web.py

This PR just tests the code from @alexandermendes

IIIF by @alexandermendes

---

pybossa/importers/iiif.py
test/test_importers/test_iiif_importer.py

Oops, turns out my tests weren't quite up to scratch - this should fix it!

Fix IIIF importer

---

cli.py

This will allow to reset a project to its initial state.
You can run the command like this:
``` python
python cli.py clean_project project_id skip_tasks
```
Project_id should be the project ID (integer) and skip_tasks (Boolean)
True or False.
If you run the command without the skip_tasks argument, everything will
be deleted. If you want to keep the tasks, and remove all the taskruns
and results, as well as reset the stats of the project, pass the True
argument.

Add clean project method.

---

pybossa/api/api_base.py
pybossa/api/project.py
test/test_api/test_project_api.py
test/test_api/test_task_api.py

Seems to do the job but let me know if you have any suggestions for improving this!

Add stats param to project endpoints

---

circle.yml
pybossa/default_settings.py
settings_local.py.tmpl

fix(settings): add missing settings.

---

cli.py

This PR allows to re-create all the missing webhooks of a project.
For example, when you have a project running for a few months, and later
on you want to start analyzing everything. All you have to do is to use
the cli.py client library to create them:
```python
python cli.py create_webhooks projectID
```
Where projectID is the projectID that you want to populate with. NOTE:
the script does not recreate previous webhooks, those ar respected.

feat(webhooks): add cli command to create webhooks.

---

pybossa/sched.py

fix limit in locked scheduler

---

pybossa/cache/__init__.py
pybossa/core.py
pybossa/feed.py
pybossa/util.py

- Add utility function `util.redis_cache_is_enabled`
- Only call `setup_scheduled_jobs` if cache is enabled.
- Only call `get_news` if cache is enabled.

Handle redis cache disabling according to docs.

---

.gitignore
pybossa/util.py

- `util.redis_cache_is_enabled` should of course use string.
- some spaces added by autopep8
- update gitignore for some other virtual environment names

Fix no redis typo

---

.gitignore
FUNDING.yml
README.md
cli.py
pybossa/api/api_base.py
pybossa/api/task_run.py
pybossa/cache/__init__.py
pybossa/core.py
pybossa/default_settings.py
pybossa/feed.py
pybossa/sched.py
pybossa/util.py
settings_local.py.tmpl
setup.py
test/test_api/test_task_api.py
test/test_api/test_taskrun_api.py
test/test_cache/test_site_stats.py
test/test_ldap.py
test/test_view/test_flickr.py
test/test_view/test_twitter.py

Test it against migrate-python3 branch.

Integrate master python3

---

cli.py
pybossa/contributions_guard.py
test/test_contributions_guard.py

Fixes: [#1969](https://github.com/Scifabric/pybossa/issues/1969)

Ensure that retrieve_timestamp returns a string and not bytes

---

Vagrantfile
contrib/pybossa.sh
contrib/server.sh

Use bash scripts to setup everything.

fix(vagrant): remove ansible and use bash.

---

cli.py

fix: remove duplicated method.

---

setup.py

Create a new PR from dependabot because we've upgraded master.

chore: bump lxml version.

---

setup.py

Create a new PR because we've changed master code.

chore: bump httplib2 version.

---

setup.py

Create a new PR as we've changed the code.

chore: bump cryptography version.
