- pybossa/core.py
- pybossa/extensions.py
- pybossa/model/task_run.py
- pybossa/sentinel/__init__.py
- setup.py
- test/factories/__init__.py
- test/factories/auditlog_factory.py
- test/test_authorization/test_auditlog_auth.py
- test/test_forms.py
- test/test_model/test_webhooks.py
- test/test_mofa.py
- test/test_repository/test_auditlog_repository.py
Includes the following changes. Also merged changes from #996 up to 5399cf237be74d1434cbd880575f9f7e9995fb1d
- Remove Gravatar libraries and references to them in both code and templates (merge too PyBossa/crowdcrafting-theme#47 and PyBossa/pybossa-default-theme#55).
- Fix and completes some tests in auditlog authorization module.
- Default Sentinel module to use a normal StrictRedis connection when used outside of an application context.
- Create rq.Queue objects explicitly.
> Small fixes refactors

- setup.py
Newest Pyrax is causing slowdowns currently.
This issue needs investigation.
Downgrade it for now to be on the safe side.
> Downgrade Pyrax Rackspace uploading module

- setup.py
Ubuntu 12.04 novaclient needs six version minimum 1.9.0.
Somehow this error does not occur on Ubuntu 14.04.
Because our production system still run Ubuntu 12.04
this fix is needed for a fresh virtualenv.
> Fix dependency issue on Ubuntu 12.04

- doc/install.rst
- setup.py
Upgrade pyrax. 1.9.4 seems working great finally.
Also fix urllib3 ssl issues for python below 2.7.9 (like in Ubuntu 12.04). Details:
http://stackoverflow.com/a/29099439/756056
> Issue ssl and pyrax

- pybossa/core.py
- pybossa/default_settings.py
- pybossa/uploader/__init__.py
- pybossa/uploader/rackspace.py
This will speed up a lot all the URL handling within the CDN.
> Cache the URL for external resources.

- setup.py
pbr was updated on Mai 18 which is not working with pyrax and novaclient. Hopefully this will be fixed in future.
> fix build error because of pbr 1.0

- alembic/versions/ac115763654_remove_completed_column_from_project.py
- pybossa/model/__init__.py
- pybossa/model/project.py
- pybossa/repositories/project_repository.py
Closes #1101.
After some time, I realised that maybe the best way of solving #1101 was to simply remove the 'completed' attribute from projects. Projects has already a lot of fields that are unused, but, most importantly, we are currently not using this anywhere in the code. The way we know whether a project is complete is with the overall progress function from the projects cache module. And I believe this is a good place for it to be, I don't really consider 'completed' an attribute of a project, but a consequence of the state of its tasks and task runs, so I would not store it in the Project model class.
> Issue 1101 completed projects

- pybossa/hateoas.py
This PR removes unnecessary queries to build hateoas. Worst case scenario has been solved, saving 100 extra queries to the DB.
> Avoid stupid queries for building hateoas.

- doc/user/tutorial.rst
Removes some old templates that are no longer used and updates docs accordingly.
See PyBossa/pybossa-default-theme#87.
> Remove old templates from theme

- pybossa/model/user.py
Otherwise problems arise when later trying to update the info column, such as when a user updates their avatar.
> Add an empty default dict for info column

- pybossa/extensions.py
- pybossa/flickr_client.py
- pybossa/view/flickr.py
- pybossa/view/projects.py
- test/test_autoimporter.py
- test/test_flickr_client.py
- test/test_web.py
This PR adds an endpoint /flickr/albums that returns the flickr albums for the current user if they've previously granted access to their Flickr account. This way this information can be retrieved from the front end without having to do the OAuth flow from there. More grained Flickr related information can be added later in a similar fasuin, e.g. individual images.
Together with the sudmodule PR (PyBossa/pybossa-default-theme#105), it keeps the same functionality that existed before.
> Flickr improvements

- pybossa/jobs.py
- test/test_jobs/test_old_projects.py
When a project is old enough, the system removes it from publication warning the owner via email.
> Clean projects

- setup.py
…novaclient
See issues:
https://github.com/rackspace/pyrax/issues/544
https://github.com/rackspace/pyrax/pull/547
Since 2015-12-18 python-novaclient 3.x was released. It removed deprecated
novaclient.v1_1 which was needed by pyrax.
Pyrax needs to fix this!
> Fix depracated novaclient 1.1 dependency for pyrax by pinning python-novaclient

- setup.py
Flask-misaka v0.4.0 uses the updated API from misaka v2.0.0 (which is not a PyBossa requirement), so restricting Flask-misaka to <0.4.0 to maintain compatibility.
> Pin Flask-misaka

- pybossa/core.py
This provides a hook for a list of plugins available on the server.
I'm redesigning some PyBossa plugins, along with a theme, and I'm trying to make everything as modular as possible. By providing this variable we can write a theme that doesn't rely on a plugin but will make use of it if available. For example, we can put something like this in our templates:
```
{% if 'pybossa_plugin' in plugins %}
<a href="{{ url_for('plugin.index') }}">Some Plugin</a>
{% endif %}
```
Otherwise, we can either not use `url_for` and accept a broken link, or use `url_for` and have the page crash, if for some reason the plugin isn't available. What do you think?
> Add hook for available plugins

- setup.py
m2crypto old versions has compatibility issues with new Openssl versions.
The newest m2crypto compiles flawless.
> upgrade m2crypto

- pybossa/api/api_base.py
- pybossa/api/task.py
- test/test_api/test_task_api.py
When a task has been completed, and the redundancy is increased,
then that task should be put into the pool again. This Commit fixes this
issue.
> Update task.state when redundancy is changed.

- .travis.yml
- alembic/versions/d1add5e3e65e_projects_stats.py
- pybossa/cache/helpers.py
- pybossa/cache/project_stats.py
- pybossa/cache/projects.py
- pybossa/exporter/csv_export.py
- pybossa/exporter/json_export.py
- pybossa/jobs.py
- pybossa/model/event_listeners.py
- pybossa/model/project_stats.py
- pybossa/view/projects.py
- setup.py
- test/test_cache/test_cache_helpers.py
- test/test_cache/test_cache_projects.py
- test/test_jobs/__init__.py
- test/test_jobs/test_project_stats.py
- test/test_privacy.py
- test/test_stats.py
- test/test_web.py
PYBOSSA has been using Redis to store this information, however this becomes "problematic" when there are millions of rows in the database, as a cold start will make things really slow. Thus, instead of using a materialized view (this cannot be used because we've tons of different SQL queries that cannot fit into one query) we'll use the same code as before but storing the info in a new table. This will make things much faster.
> Issue project stats in a new table

- pybossa/view/leaderboard.py
- test/test_web.py
Return 404 if the leaderboard is not configured in the settings file.
> Fix #1641.

- pybossa/view/google.py
- test/test_view/test_google.py
> Remove 'response_type' from request_token_params

- pybossa/model/project.py
This is a quick fix for a situation where I have the project and need to retrieve its associated category. Hopefully there's no reason why we shouldn't add this.
> Add category_id to project public fields

- pybossa/exporter/__init__.py
- settings_local.py.tmpl
- test/test_web.py
This PR allows to specify a key from the task.info task_run.info or
result.info to be used as the root key when exporting the data as CSV.
For example, you could have in the task_runs the following:
```json
info: answer: [{foo: 1}]
```
And another one like this:
```json
info: {answer:[{foo: 1}, {foo: 2}]}
```
In such cases, you may want to tell PYBOSSA to use answer within info as
the root to flatten the data.
> Make the exporter more flexible.

- Vagrantfile
Update the Vagrantfile to avoid ERROR: problem running ansible_hosts --list ([Errno 8] Exec format error), which happens on Windows as the hosts file gets marked as executable when /vagrant/provisioning/hosts is used.
> Add Windows fix to Vagrantfile

- pybossa/repositories/__init__.py
As results can be created with a `null` info field I think we should add a check here, otherwise attempting to search this info field can throw errors.
> Check info is not null in handle_info_json

- pybossa/repositories/__init__.py
- test/test_repository/test_task_repository.py
This new PR will allow using the @> Postgresql operator within the info fields. Basically, you will be able to get all the domain objects that follow a path like this:
```
http://localhost:5001/api/taskrun?info={"answer":[{"relevant":false}]}
```
NOTE: you might need to escape your URL if you are using it directly from JS, otherwise chrome does the work for you.
> Api search

- test/test_contributions_guard.py
- test/test_jobs/test_maintenance.py
- test/test_jobs/test_news.py
- test/test_jobs/test_schedule_jobs.py
- test/test_jobs/test_webhooks.py
- test/test_news.py
Hello, I noticed that some tests fail if the default value for `REDIS_SENTINEL` in settings_test is changed and sentinel is not running on localhost. With these changes the address of sentinel is taken from settings_test.
> redis connection from settings test

- .gitmodules
- alembic/versions/d317dc38cf39_add_user_pref_to_user.py
- pybossa/cache/users.py
- pybossa/core.py
- pybossa/forms/fields/__init__.py
- pybossa/forms/fields/time_field.py
- pybossa/forms/forms.py
- pybossa/forms/validator.py
- pybossa/model/user.py
- pybossa/util.py
- pybossa/view/account.py
- settings_upref_mdata.py.tmpl
- setup.py
- test/test_forms.py
- test/test_web.py
Hello,
We just added a feature to set user preferences for their preferred languages/locations and metadata such as users work hours, expertise about a user on account filing form.  The user preferences and metadata would be available and modified from account profile page.  https://github.com/Scifabric/docs.pybossa.com/pull/24 has documentation on this feature along with screenshots. In future, this could be useful for building a new scheduler that can assign tasks to a user based on his/her preferences set.
> user pref and metadata for user accounts

- pybossa/forms/forms.py
- pybossa/importers/iiif.py
- pybossa/importers/importer.py
- test/test_importers/__init__.py
- test/test_importers/test_iiif_importer.py
- test/test_web.py
Here's an importer to generate tasks from [IIIF](http://iiif.io/) manifests. Just pass in the manifest URL and a task will be created for each canvas. Here's an example from the British Library to try it out with:
https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589088.0x000002/manifest.json
Will add the docs too.
> Add IIIF importer

- pybossa/importers/iiif.py
- test/test_importers/test_iiif_importer.py
Within the IIIF API, it occurred to me that, although it wouldn't happen for the majority of collections, it is in fact possible to have multiple images defined for each canvas, where a canvas is a container onto which an image (or multiple images) are painted. This PR ensures that all images for all canvases are imported. In 99% of cases this probably doesn't change anything but I think the option should be built in here, just in case. I'll send a documentation update to make it clearer how the importer works.
> Import all images from all canvases

- provisioning/playbook.yml
A missing command  " redis-server contrib/sentinel.conf --sentinel " added for the virtual machine restart.
> Added a new line on the documentation

- pybossa/default_settings.py
Obviously this should be changed in the local settings but adding a default means that at least it won't fail and cause confusion for people that already have a VM setup (and their settings_local.py file already created).
Closes #1841
> Add CRYPTOPAN_KEY to default settings

- pybossa/exporter/json_export.py
- pybossa/jobs.py
- pybossa/newsletter/__init__.py
- setup.py
The job deletes the account, but fails to send the email to the user when the account has been deleted because the MAILCHIMP Key does not exist (which could be true, because the server is not using it). This PR fixes it.
> Fix delete for when no mailchimp key.

- pybossa/model/event_listeners.py
So that category_id shows up in the update feed (see https://github.com/Scifabric/pybossa/pull/1865)
> Get category_id in on_taskrun_submit event listener

- pybossa/api/project.py
- test/test_api/test_project_api.py
If the category_id does not exist, it raises a BadRequest error.
> Allow to specify a category_id when creating a project.

- pybossa/api/api_base.py
- test/test_api/test_api_helpingmaterial.py
Right now when you send an API POST request to helpingmaterial with a file and some JSON data, it fails. This PR should fix it.
> Allow helpingmaterial to get JSON when sending files.

- pybossa/cache/__init__.py
Both the wrappers `cache` and `memoize` called `sentinel.master.setex`
even when `PYBOSSA_REDIS_CACHE_DISABLED` is set.
> Fix so that redis is not called when REDIS is disabled.

- pybossa/core.py
- pybossa/feed.py
- pybossa/util.py
- test/test_cache/test_site_stats.py
Revert back changes introduced by @kod-kristoff .
The changes caused several problems. For example, all background jobs were disabled, and those jobs are required to run a PYBOSSA server.
Also, the cache is different from why PYBOSSA uses Redis/Sentinel. Redis is used for caching some queries, but also, for handling information via the API (like stats).
For this reason, these commits revert back all the changes and restore the default behavior.
> fix(redis): cache was bad handled.

- alembic/versions/a791f9de9ac3_add_new_notify_column_to_user.py
- pybossa/jobs.py
- pybossa/model/event_listeners.py
- pybossa/model/user.py
- setup.py
- test/test_api/test_taskrun_api.py
- test/test_jobs/test_delete_inactive_accounts.py
This new PR fixes a problem with the deletion of accounts.
First it simplifies the process:
* We check for users that have sent a taskrun more than X months ago.
* For those users, we send an email saying that if in the coming month
they do not contribute again, their accounts will be deleted.
* We then run another job that will check for users that have been
notified one month ago or more, if they exist, those accounts are
deleted.
* As soon as an account submits a taskrun the notified_at value changes
to null, disabling the deletion.
> fix(gdpr): delete inactive accounts.

- cli.py
This fix is described here https://stackoverflow.com/questions/60923607/multiple-issues-trying-to-install-pybossa
For some reason the problem with '\x' appears with AWS RDS while no problem with GCP CloudSQL
> Fix unicode problem with db

- pybossa/api/__init__.py
- test/test_api/test_project_api.py
The API endpoint http://server.com/api/project/<id>/userprogress now
allows you to pass the argument query ?external_uid=YOUR_EXTERNAL_UID to
get the progress of that external user.
> feat(userprogress): allow external_uid as a parameter.
